TEMPLATES = {
    "lose_streak": [
        "À ce stade, {mention}, {streak_len} défaites d'affilée avec un magnifique {k}/{d}/{a}, c'est presque une tradition ! 🎭",
        "Encore une partie perdue ? {streak_len} de suite sponsorise tes défaites {mention}… surtout avec ce {k}/{d}/{a} 😭",
        "Avec {streak_len} défaites et un score de {k}/{d}/{a}, même le Baron Nashor a pitié de {mention} 💀",
        "{streak_len} lignes rouges dans l'historique de {mention}… et ce {k}/{d}/{a} aide pas à inverser la tendance 🎬",
        "{mention} continue la collection de défaites : {streak_len} d'affilée avec {k}/{d}/{a} 📉",
        "{mention} enchaîne une magnifique série de {streak_len} défaites avec un sublime {k}/{d}/{a} 📉",
        "{streak_len} défaites d'affilée… Riot va t'envoyer en coop vs IA pour une remise à niveau {mention} ({k}/{d}/{a}) 🤖",
        "Encore une rouge pour {mention}. À ce rythme-là, le MMR appelle le SAMU 🚑 ({k}/{d}/{a})",
        "{mention} transforme la soloQ en escape game : impossible de sortir de cette lose streak ({k}/{d}/{a}) 🔒",
        "{streak_len} défaites de suite pour {mention}. Même les minions ont plus de winrate 😭 ({k}/{d}/{a})",
        "{mention} essaie une nouvelle stratégie : perdre {streak_len} de suite pour rejoindre ses copains les golems ({k}/{d}/{a}) 🧠",
        "On appelle ça une série noire {mention} ({streak_len} loses de suite). Riot a capté que tu valais Iron IV 💀 ({k}/{d}/{a})",
        "{mention} farm les défaites plus vite qu'un Smolder stack son passif 📈 ({k}/{d}/{a})",
    ],

    "win_streak": [
        "{streak_len} victoires d'affilée pour {mention} ! Ça va tag Caliste à la prochaine soloQ 🚀",
        "{streak_len} wins de suite, propre pour {mention} 🏆",
        "L'autoroute des LP pour {mention} : {streak_len} victoires d'affilée 🛣️",
        "{mention} en mode rouleau compresseur : {streak_len} wins consécutives et un {k}/{d}/{a} qui fait peur 💪",
        "{mention}, {streak_len} wins de suite… partage la faille de l'algorithme stp ! 🤖",
        "{mention} est actuellement en suspicion de smurfing après ses {streak_len} wins d'affilée 🚨",
        "{streak_len} wins de suite pour {mention}. Le boosting est devenu légal ou quoi ? 🤨",
        "{mention} le Max Verstappen sur l'autoroute des LP ({streak_len} wins de suite) 💸",
        "Nouvelle série Netflix : “{mention} et l'autoroute des LP” ({streak_len} épisodes déjà) 🎬",
        "{mention} est en train de transformer la ranked en tutoriel Riot ({streak_len} win streak) 📚",
        "{streak_len} wins d'affilée… Faker veut connaître les réglages de {mention} 🐐",
        "{mention} smurf tellement fort son op.gg provoque des remakes 👀 ({k}/{d}/{a})",
        "Le MMR de {mention} monte plus vite que le prix de l'escence 📈 ({k}/{d}/{a})",
    ],

    "big_loss": [
        "Thebausffs serait presque fier de toi {mention} avec ton magnifique {k}/{d}/{a} 💀, sauf que lui c'est pour gagner 😎",
        "Petite game en {k}/{d}/{a} pour {mention} 😅 Besoin d'un cours de farming sous tour ou d'un verre d'eau ? 🍹",
        "Si la défaite était un art, {mention} serait Picasso avec son {player_champ} en {k}/{d}/{a} 🎨😭",
        "Alors {mention}, {best_enemy_champ} ({best_enemy_score}) t’a montré comment jouer son champion correctement après ce {k}/{d}/{a} ? 🤯👏",
        "On t'a payé combien {mention} 💸 pour sortir {player_champ} en {k}/{d}/{a} contre {best_enemy_champ} ({best_enemy_score})? 😏",
        "{mention} Ton/Ta {player_champ} voulait participer à un festival de kills… toi tu as surtout participé au compteur de morts avec ce {k}/{d}/{a} 💀",
        "Des éclats de rire à chaque respawn de {mention}… surtout après ce {k}/{d}/{a} 🎤",
        "La statistique la plus surréaliste du match : {mention} en {k}/{d}/{a} 👻",
        "Ton feed a penché la game plus fort que la Tour de Pise, {mention} 🤷 ({k}/{d}/{a})",
        "Même Gandalf ferait demi-tour en voyant ce {k}/{d}/{a}, {mention} 🔄",
        "{mention} a terminé la partie en {k}/{d}/{a}. Les ennemis ont demandé si c'était un challenge TikTok 💀",
        "{player_champ} de {mention} a participé à tous les teamfights… en noir et blanc ({k}/{d}/{a}) ⚰️",
        "Avec un {k}/{d}/{a} pareil, même les bots intro auraient spam ff {mention} 😭",
        "{mention} a testé la fonctionnalité “respawn simulator” sur {player_champ} 🔄 ({k}/{d}/{a})",
        "{best_enemy_champ} ({best_enemy_score}) a reçu un remboursement de LP après avoir affronté le {player_champ} de {mention} 🤝 ({k}/{d}/{a})",
        "{mention} a nourri plus de monde qu’un resto du coeur aujourd’hui 🍽️ ({k}/{d}/{a})",
        "{mention} Est le vrai carry de l'équipe, mais de l'équipe adverse 🤔 ({k}/{d}/{a})",
        "{mention} a plus été farmé par l'équipe adverse que les sbires canons ⚔️ ({k}/{d}/{a})",
        "{mention} ({k}/{d}/{a}) n'avait rien demandé… mais {best_enemy_champ} ({best_enemy_score}) lui a offert une humiliation publique 🎪",
    ],

    "carried_but_lost": [
        "Merci à {worst_team_champ} ({worst_team_score}) pour le feed… même un {k}/{d}/{a} comme celui de {mention} n'a pas suffi 🏋️",
        "Avec tout le feed de {worst_team_champ} ({worst_team_score}), {mention} portait une team plus lourde que son ego avec son {k}/{d}/{a} 💪",
        "Mission carry pour {mention} : {k}/{d}/{a}. Résultat ? Ses mates avaient choisi le lâcher-prise 🤷",
        "Ton KDA ({k}/{d}/{a}) parle d'exploit {mention}, mais ton équipe farmait le gromp pendant le dernier fight 🐸",
        "Avec un {k}/{d}/{a} pareil, tu as lâché un petit report à {worst_team_champ} ({worst_team_score}), {mention} ? 👀",
        "Il paraît que ça joue trop le KDA {mention}… vu le {k}/{d}/{a}, {worst_team_champ} confirme :3",
        "Le {k}/{d}/{a} de {mention} méritait la win, mais la draft avec {worst_team_champ} contre {best_enemy_champ} disait non 😵",
        "Ton {player_champ} a fait le taf avec {k}/{d}/{a}, {mention}, mais le reste de l'équipe jouait en mode spectateur 🍿",
        "{mention} a tout donné avec son {k}/{d}/{a}, mais ses mates avaient des objectifs différents 🧳",
        "Impossible de porter une team plus lourde que ça sans permis poids lourd {mention} 🚛 ({k}/{d}/{a})",
        "{mention} jouait la qualif Worlds pendant que son équipe jouait ARAM mid ({k}/{d}/{a}) 🎯",
        "Le {player_champ} de {mention} méritait la victoire. Le reste de la team méritait une enquête 🔍",
        "{mention} termine en {k}/{d}/{a} et découvre le fameux “jg diff”, “bot diff”, “top diff” simultané 🎰",
        "Même Atlas porterait moins lourd que les mates de {mention} 🏋️ ({k}/{d}/{a})",
        "{mention} a essayé de 1v9. Riot rappelle que ce mode n’existe pas officiellement 😭 ({k}/{d}/{a})",
        "{worst_team_champ} avec son {worst_team_score} a transformé la game en mission impossible pour {mention} 💣 ({k}/{d}/{a})",
    ],

    "big_win": [
        "{mention}, {player_champ} a été un dieu avec {k}/{d}/{a} 🚀",
        "Solide {k}/{d}/{a} du {player_champ} de {mention} en {queue} 👏",
        "{mention} Ton {player_champ} a récupéré plus de kills que le Père Noël distribue de cadeaux 🎁 ({k}/{d}/{a})",
        "Le {k}/{d}/{a} de {mention} vaut bien un Oscar 🎬",
        "Ton {player_champ} a fait des ravages avec ce {k}/{d}/{a}, {mention} 🏆",
        "{mention} Ton {player_champ} a fait du ménage mieux qu'un aspirateur Dyson : {k}/{d}/{a} 🌪️",
        "La justice est faite, {mention} : {k}/{d}/{a} stylé ✊",
        "{mention} Ton {player_champ} a été en feu avec ce {k}/{d}/{a} 🔥",
        "Tu devrais facturer tes services de smurfing {mention} : {k}/{d}/{a} 💰",
        "{mention} a transformé la faille en zone sinistrée avec {player_champ} 🔥 ({k}/{d}/{a})",
        "{player_champ} joué par {mention} vient officiellement d’être classé arme de destruction massive ({k}/{d}/{a}) ☢️",
        "Le {k}/{d}/{a} de {mention} ressemble à une game jouée contre des bots intro 😭",
        "{mention} a tellement carry que ses mates vont prendre des LP par procuration 💼 ({k}/{d}/{a})",
        "Les ennemis ont signalé {mention} pour smurf après ce {k}/{d}/{a} 🚨",
        "{mention} a fait plus de dégâts mentaux que physiques dans cette game 🧠 ({k}/{d}/{a})",
        "Performance certifiée illégale en soloQ de la part de {mention} 📜 ({k}/{d}/{a})",
        "{player_champ} de {mention} avait visiblement une vengeance personnelle contre l’équipe ennemie 💀 ({k}/{d}/{a})",
    ],

    "low_kda_but_win": [
        "{mention}, {worst_enemy_champ} ({worst_enemy_score}) a tout fait pour te laisser gagner malgré ce {k}/{d}/{a} 😭",
        "La victoire de {mention} avec ce {k}/{d}/{a} est aussi surprenante que l'ananas sur une pizza 🍍",
        "On dirait que {worst_enemy_champ} ({worst_enemy_score}) organisait un barbecue avec {mention} ({k}/{d}/{a}) pendant que {best_team_champ} gagnait la game 🍖 ({best_team_score})",
        "{mention} Ton {player_champ} a passé le match en mode sieste ({k}/{d}/{a}) 😴",
        "Ils avaient combien d'afk pour te laisser gagner avec un {k}/{d}/{a} pareil {mention} ? 👀",
        "Trop de KS de la part de {best_team_champ} ({best_team_score}), du coup personne n'a vu le carry de {mention} en {k}/{d}/{a} 👻",
        "GG {mention}, on t'a vu survivre par miracle avec ton {k}/{d}/{a} 😂",
        "{k}/{d}/{a}… Thebausffs serait fier de toi {mention}, ton équipe un peu moins 🤡",
        "Tu nous fais une Sardoche {mention} ? Avec ce {k}/{d}/{a}, ajoute {best_team_champ} pour duo 😂",
        "{mention} gagne avec un magnifique {k}/{d}/{a}. La justice a quitté la faille aujourd’hui ⚖️",
        "Victoire confirmée pour {mention} malgré un KDA qui ferait pleurer un coach esport 😭 ({k}/{d}/{a})",
        "{mention} a été spectateur premium de cette victoire 🎟️ ({k}/{d}/{a})",
        "{mention} Le plus gros hold de cette partie : réussir à se faire carry avec ce {k}/{d}/{a} 🪂",
        "{mention} prouve qu’on peut gagner sans participer activement à la game 🧠 ({k}/{d}/{a})",
        "GG à {mention}, survivre assez longtemps pour être carried reste une compétence 💪 ({k}/{d}/{a})",
        "Le matchmaking a décidé d’offrir des LP à {mention} aujourd’hui 🎁 ({k}/{d}/{a})",
        "{best_team_champ} a joué pour deux ({best_team_score}) pendant que {mention} testait les buissons de la map 🌿 ({k}/{d}/{a})",
    ],

    "very_high_damage": [
        "{mention} a transformé la game en stand de tir : {damage} dégâts avec {player_champ} et un {k}/{d}/{a} 💥",
        "{player_champ} version nucléaire pour {mention} : {damage} dégâts et {k}/{d}/{a} ☢️",
        "{mention} a tapé si fort ({damage} dégâts) que même les tours ont demandé un nerf 🏰 ({k}/{d}/{a})",
        "On parle de {damage} dégâts en {queue}… {mention}, t'avais la haine avec ce {k}/{d}/{a} ? 😡",
        "{mention} {player_champ} a confondu la faille avec un sac de frappe : {damage} dégâts et {k}/{d}/{a} 🥊",
        "{mention} a fait plus de dégâts que toute une équipe Clash : {damage} 💀 ({k}/{d}/{a})",
        "Les ennemis vont vérifier leurs options graphiques après les {damage} dégâts de {mention} 👓 ({k}/{d}/{a})",
        "{player_champ} MVP du DPS club : {damage} dégâts infligés par {mention} 🔥 ({k}/{d}/{a})",
        "{mention} a joué en mode tutoriel pour les ennemis : {damage} dégâts et {k}/{d}/{a} 📈",
        "{damage} dégâts. Oui oui. {mention}, pense à laisser des champions pour les autres la prochaine fois 😅 ({k}/{d}/{a})",
        "{mention} a distribué {damage} dégâts comme un influenceur distribue des codes promo 💥 ({k}/{d}/{a})",
        "{damage} dégâts pour {mention}. Les HP ennemis ont porté plainte 📄",
        "{player_champ} de {mention} tapait si fort que même les spectateurs perdaient des PV ⚡ ({k}/{d}/{a})",
        "{mention} a transformé la frontline ennemie en compilation best-of morts 🪦 ({damage} dégâts)",
        "Les dégâts de {mention} dépassent probablement le PIB de certaines régions 🌍 ({damage})",
        "{damage} dégâts… le clavier de {mention} mérite une prime de performance ⌨️",
        "Même Riot ne comprend pas comment {mention} a sorti {damage} dégâts 🤯 ({k}/{d}/{a})",
        "{mention} a joué comme si chaque ennemi lui devait de l'argent 💸 ({damage} dégâts)",
    ],

    "pentakill": [
        "PENTAKILL 💥 {mention} a supprimé toute l'équipe avec {player_champ} ({k}/{d}/{a}) !",
        "Ils vont s'en souvenir longtemps… PENTAKILL de {mention} sur {player_champ} 🔥 ({k}/{d}/{a})",
        "{mention} a activé le mode boss final : PENTAKILL avec {player_champ} 👑 ({k}/{d}/{a})",
        "Un, deux, trois, quatre… cinq ! PENTAKILL signé {mention} 🖐️ ({k}/{d}/{a})",
        "La faille n'était pas prête : PENTAKILL de {mention} avec {player_champ} 💀 ({k}/{d}/{a})",
        "{player_champ} a rayé l'équipe ennemie du patch notes : PENTAKILL pour {mention} ⚔️ ({k}/{d}/{a})",
        "Même le shoutcaster a perdu sa voix : PENTAKILL de {mention} 🎙️ ({k}/{d}/{a})",
        "PENTAKILL confirmé. Merci {mention} pour ce moment historique ✨ ({k}/{d}/{a})",
        "{mention} a cliqué trop fort : résultat, un PENTAKILL avec {player_champ} 🖱️ ({k}/{d}/{a})",
        "On appelle ça un crime de guerre… PENTAKILL de {mention} 🚨 ({k}/{d}/{a})",
    ]
}